---
monitor:
  portName: tty.usbserial-1440
  bandRate: 6
  parity: 0
  dataBits: 3
  stopBits: 0
  commands: null
  hexMode: false
  withReturn: true
  withNewLine: true
  opened: false
interact:
  portName: null
  bandRate: 6
  parity: 0
  dataBits: 3
  stopBits: 0
  commands: null
  hexMode: false
  withReturn: true
  withNewLine: true
  opened: false
